export ZSH=$HOME/.oh-my-zsh

ZSH_THEME=""

plugins=(git)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:~/.config/composer/vendor/bin/:$PATH

source $ZSH/oh-my-zsh.sh

alias changelog='git log `git describe --tags --abbrev=0`..HEAD --pretty=format:%s'
alias git='LANG=en_US git'
alias ifstat="ifstat -S -i eth0 -i wlan0"
alias docker-ip='docker inspect --format "{{ .NetworkSettings.IPAddress }}"'
alias meteo="curl -4 http://wttr.in/Toulouse"
alias doco="docker-compose"
alias "49.3"="git push --force"
alias dive="docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/bin/docker wagoodman/dive:latest"

# 10 most used commands
function tellmylife() {
    history | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl |  head -n10
}

. ~/.rupaz/z.sh

if [ -e ~/.zshrc_local ]; then
    . ~/.zshrc_local
fi

fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure

zstyle :prompt:pure:execution_time color '#F55000'
zstyle :prompt:pure:git:arrow color '#AAAA00'
zstyle :prompt:pure:git:stash color '#AAAA00'
zstyle :prompt:pure:git:branch color '#999999'
zstyle :prompt:pure:git:branch:cached color '#FFFFFF'
zstyle :prompt:pure:git:action color '#FFFFFF'
zstyle :prompt:pure:git:dirty color '#FFFF00'
zstyle :prompt:pure:host color '#FFFFFF'
zstyle :prompt:pure:path color '#FFFFFF'
zstyle :prompt:pure:prompt:error color '#990000'
zstyle :prompt:pure:prompt:success color '#009933'
zstyle :prompt:pure:prompt:continuation color '#F55000'
zstyle :prompt:pure:git:stash show yes
